# Generated by Django 4.2.7 on 2023-11-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.TextField(max_length=500, verbose_name='Address')),
                ('project', models.CharField(max_length=50, verbose_name='Project Code')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
