# Generated by Django 4.2.7 on 2023-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=500, verbose_name='Address'),
        ),
    ]
