# Generated by Django 4.2.7 on 2023-11-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(choices=[], on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
