# Generated by Django 4.2.7 on 2023-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='customer',
            field=models.ForeignKey(choices=[('Proj1_Kiran', 'Proj1_Kiran')], on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
