# Generated by Django 4.2.7 on 2023-11-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
