# Generated by Django 4.1.5 on 2023-03-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mechanical",
        ),
    ]
